pipeline {
    agent any

    tools {
        maven "maven"
    }
    

    stages {
        stage('Build') {
            steps {
		
                git 'https://github.com/SiddharthVarshney/progressive-proj.git'

                // Run Maven on a Unix agent.
                bat "mvn clean install -Dmaven.test.skip=true"

                bat "docker rm webtest"
                bat "docker rmi webtest"
                bat "docker build -t webtest ."
                bat "docker run --name webtest -it --rm -p 8888:8080 webtest"


            }

            }
        }

  post {
        failure {
		echo "Application failed ***********" 
        }

    }    

}
